"""Add User and room owner_id

Revision ID: 3e41850b794e
Revises: 5ed452d1da2d
Create Date: 2026-04-22 21:45:28.242177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e41850b794e'
down_revision: Union[str, Sequence[str], None] = '5ed452d1da2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'users' not in tables:
        op.create_table('users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('picture', sa.String(), nullable=True),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('created_at', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
            batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    columns = [col['name'] for col in inspector.get_columns('rooms')]
    if 'owner_id' not in columns:
        with op.batch_alter_table('rooms', schema=None) as batch_op:
            batch_op.add_column(sa.Column('owner_id', sa.String(), nullable=True))
            batch_op.create_index(batch_op.f('ix_rooms_owner_id'), ['owner_id'], unique=False)
            batch_op.create_foreign_key('fk_rooms_owner_id', 'users', ['owner_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rooms_owner_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_rooms_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
